### ISSUE TITLE
Tmux pane top

### ISSUE THREAD

**Issue by huyvohcmc** [ahmedelgabri/dotfiles#20]
Can you increase the position of tmux pane top to make it seems like it a border-bottom of the status bar?
<img width="1280" alt="screen shot 2018-12-01 at 11 58 26 am" src="https://user-images.githubusercontent.com/17645203/49324448-7269c500-f560-11e8-9ee0-66ec1f3e2361.png">
In my case there's a small gap and it just doesn't look good.

**Comment by ahmedelgabri** [comment]
As far as I know, this can't be done, it is a tmux limitation. But if you find a solution please let me know.
