### ISSUE TITLE
Question about stow

### ISSUE THREAD

**Issue by ElModdy** [ahmedelgabri/dotfiles#21]
Hi,
I'm new to Stow and I'm having difficulties understanding how to manage the dotfiles properly.
My quest is: If you have to add a file, do you create it in the repo and then relaunch stow every time?
I know my question is off topic and I will remove it if you don't want to answare me but I really appreciate any kind of help.

**Comment by ahmedelgabri** [comment]
First, there is no such thing as a stupid question 😊(I changed the title). We all do have difficulties with understanding things & we only can learn by doing or seeking help so there is no problem with that.

The main idea behind `stow` is to symlink folders to other locations following the source structure, for example. In this repo I run `stow` like this

```sh
stow --target="$HOME" --dir=~/.dotfiles files
```

What is this basically doing is that it will symlink all the files & folders inside `files/` to the home directory. Like a 1-1 mapping between `files/` & `~/`

For example, if you check my [`.config`](https://github.com/ahmedelgabri/dotfiles/tree/master/files/.config) folder you will see that it contains folders & files too but when I run stow it will symlink the full `.config` directory if didn't exist but if it exists & these folders doesn't exist it will symlink these folders only etc...

So yes, when you add a new file you will need to run stow again.

I hope this answered your question & I highly recommend that you read the [`stow` manual](https://www.gnu.org/software/stow/manual/stow.html)

**Comment by ElModdy** [comment]
Thanks a lot for the answare.
So for the existing files I can work on their "original" direcotry and they will be updated also in the repo but for the new one I have to move to the repo, work there and then launch stow to create the link.
I'm sorry for my bad english hope my quest is clear enough.

**Comment by ahmedelgabri** [comment]
stow only handling the symlinking, so once the file is symlinked any change you do to that file will be reflected already. Whether you do this change in repo or the symlinked file.

But when you add a new file, you will need to run stow to link it yes.

**Comment by ElModdy** [comment]
I promise this is the last quest.
So it's just a matter of preference but you modify the symlinked file or in the repo?

**Comment by ahmedelgabri** [comment]
Yes, it doesn't matter. And by the way this has nothing to do with stow, it's how symlinks work in general.
